plugins { id "com.android.application" }

android {
    namespace "com.penecho.board"
    compileSdk 34

    aaptOptions {
        // assets/termux.apk 不压缩存储(PackageInstaller 读取更稳)
        noCompress "apk"
    }

    defaultConfig {
        applicationId "com.penecho.board"
        minSdk 26
        targetSdk 34
        versionCode 2
        versionName "1.1"
    }

    buildTypes {
        release {
            // 自用分发:debug key 签名即可安装;不混淆(WebView 壳无此需求)
            signingConfig signingConfigs.debug
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
